export class clssubclient {
  id: string = "";
  subclientid: number = 0;
  clientid: string = "";
  subclientcode: string = "";
  subclientname: string = "";
  billinglocationcode: string = "";
  subclientcontactname: string = "";
  subclientcontactphone: string = "";
  subclientcontactemail: string = "";
  subclientdivisioncode: string = "";
  subclientstatus: boolean = false;
  createdby: string = "";
  createdon: string = "";
  companytype: string = "";
  billingcompany: string = "";
  ftpoption: string = "";
  clientname: string = "";
  copytoftpsubclientid: number = 0;
  copytoftpsubclientname: string = "";
}
